#!/bin/sh

APPDIR=$(dirname "$0")
$APPDIR/java/bin/java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/Filter_Tester_Processing.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-i586.jar:$APPDIR/lib/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/jssc.jar" Filter_Tester_Processing "$@"
